COMMENT ON TABLE flyway_schema_history IS 'Flyway 数据库迁移历史表，由 Flyway 自动维护，请勿手工修改';
COMMENT ON COLUMN flyway_schema_history.installed_rank IS '迁移安装顺序';
COMMENT ON COLUMN flyway_schema_history.version IS '迁移版本号';
COMMENT ON COLUMN flyway_schema_history.description IS '迁移描述';
COMMENT ON COLUMN flyway_schema_history.type IS '迁移类型，例如 SQL';
COMMENT ON COLUMN flyway_schema_history.script IS '迁移脚本名称';
COMMENT ON COLUMN flyway_schema_history.checksum IS '迁移脚本校验值，用于检测已执行脚本是否被修改';
COMMENT ON COLUMN flyway_schema_history.installed_by IS '执行迁移的数据库用户';
COMMENT ON COLUMN flyway_schema_history.installed_on IS '迁移安装时间';
COMMENT ON COLUMN flyway_schema_history.execution_time IS '迁移执行耗时，单位为毫秒';
COMMENT ON COLUMN flyway_schema_history.success IS '迁移是否执行成功';

COMMENT ON TABLE app_schema_marker IS '数据库基线标记表，仅保留一行，用于确认 NextOne schema 已完成初始化';
COMMENT ON COLUMN app_schema_marker.id IS '固定为 1 的单例主键';
COMMENT ON COLUMN app_schema_marker.created_at IS '数据库基线首次创建时间';

COMMENT ON TABLE app_user IS 'NextOne 用户账户与区域偏好，是所有用户数据的隔离边界';
COMMENT ON COLUMN app_user.id IS '用户唯一标识';
COMMENT ON COLUMN app_user.display_name IS '用户显示名称';
COMMENT ON COLUMN app_user.locale IS '界面语言区域代码，例如 zh-CN';
COMMENT ON COLUMN app_user.time_zone IS 'IANA 时区标识，例如 Asia/Shanghai';
COMMENT ON COLUMN app_user.created_at IS '用户创建时间';
COMMENT ON COLUMN app_user.updated_at IS '用户资料最后更新时间';
COMMENT ON COLUMN app_user.revision IS '乐观锁版本号，每次服务端修改后递增';

COMMENT ON TABLE project IS '项目表，用于组织具有明确成果的一组行动，并维护当前焦点任务';
COMMENT ON COLUMN project.id IS '项目唯一标识';
COMMENT ON COLUMN project.user_id IS '所属用户标识，用于数据隔离';
COMMENT ON COLUMN project.area_id IS '所属领域标识，当前为预留字段';
COMMENT ON COLUMN project.name IS '项目名称';
COMMENT ON COLUMN project.note IS '项目背景、目标或补充说明';
COMMENT ON COLUMN project.status IS '项目状态：ACTIVE 进行中、ON_HOLD 暂停、COMPLETED 已完成、CANCELED 已取消';
COMMENT ON COLUMN project.focus_task_id IS '项目当前唯一焦点任务标识，可为空';
COMMENT ON COLUMN project.sort_key IS '客户端生成的稳定排序键，用于手动排序';
COMMENT ON COLUMN project.created_at IS '项目创建时间';
COMMENT ON COLUMN project.updated_at IS '项目最后业务更新时间';
COMMENT ON COLUMN project.deleted_at IS '软删除时间；为空表示项目仍有效';
COMMENT ON COLUMN project.revision IS '乐观锁版本号，每次服务端修改后递增';

COMMENT ON TABLE task IS '行动任务主表，保存任务内容、执行状态、可见性、时间与精力属性';
COMMENT ON COLUMN task.id IS '任务唯一标识';
COMMENT ON COLUMN task.user_id IS '所属用户标识，用于数据隔离';
COMMENT ON COLUMN task.area_id IS '所属领域标识，当前为预留字段';
COMMENT ON COLUMN task.project_id IS '所属项目标识；为空表示独立任务';
COMMENT ON COLUMN task.title IS '任务标题';
COMMENT ON COLUMN task.note IS '任务背景、上下文或补充说明';
COMMENT ON COLUMN task.status IS '执行状态：INBOX 收件箱、READY 准备就绪、DOING 进行中、WAITING 等待中、COMPLETED 已完成、CANCELED 已放弃';
COMMENT ON COLUMN task.visibility IS '可见性：ACTIVE 活跃、SNOOZED 暂缓、SOMEDAY 以后再说';
COMMENT ON COLUMN task.deadline_at IS '任务截止时间';
COMMENT ON COLUMN task.review_at IS '计划下次回顾或重新判断的时间';
COMMENT ON COLUMN task.reviewed_at IS '最近一次完成回顾的时间';
COMMENT ON COLUMN task.waiting_for IS '等待的对象、结果或外部条件说明';
COMMENT ON COLUMN task.waiting_since IS '任务进入等待状态的时间';
COMMENT ON COLUMN task.estimate_minutes IS '预估完成任务所需分钟数';
COMMENT ON COLUMN task.energy_level IS '精力要求：LOW 低、MEDIUM 中、HIGH 高';
COMMENT ON COLUMN task.sort_key IS '客户端生成的稳定排序键，用于手动排序';
COMMENT ON COLUMN task.completed_at IS '任务完成时间';
COMMENT ON COLUMN task.canceled_at IS '任务放弃时间';
COMMENT ON COLUMN task.created_at IS '任务创建时间';
COMMENT ON COLUMN task.updated_at IS '任务最后业务更新时间，不使用同步接收时间覆盖';
COMMENT ON COLUMN task.deleted_at IS '软删除时间；为空表示任务仍有效';
COMMENT ON COLUMN task.revision IS '乐观锁版本号，每次服务端修改后递增';

COMMENT ON TABLE daily_plan IS '每日行动计划表，每个用户每天最多一条，按本地日期和时区划分';
COMMENT ON COLUMN daily_plan.id IS '每日计划唯一标识';
COMMENT ON COLUMN daily_plan.user_id IS '所属用户标识，用于数据隔离';
COMMENT ON COLUMN daily_plan.plan_date IS '计划所属的本地自然日';
COMMENT ON COLUMN daily_plan.time_zone IS '生成该计划日期时采用的 IANA 时区';
COMMENT ON COLUMN daily_plan.created_at IS '每日计划创建时间';
COMMENT ON COLUMN daily_plan.updated_at IS '每日计划最后更新时间';
COMMENT ON COLUMN daily_plan.revision IS '乐观锁版本号，每次服务端修改后递增';

COMMENT ON TABLE daily_plan_item IS '每日计划与任务的关联表，区分今日焦点和之后可做';
COMMENT ON COLUMN daily_plan_item.id IS '每日计划事项唯一标识';
COMMENT ON COLUMN daily_plan_item.daily_plan_id IS '所属每日计划标识；删除计划时级联删除';
COMMENT ON COLUMN daily_plan_item.task_id IS '关联的任务标识';
COMMENT ON COLUMN daily_plan_item.section IS '所在分区：FOCUS 今日焦点、LATER 之后可做';
COMMENT ON COLUMN daily_plan_item.sort_key IS '分区内的稳定排序键';
COMMENT ON COLUMN daily_plan_item.created_at IS '任务加入该每日计划的时间';

COMMENT ON TABLE task_event IS '任务领域事件与行动日志，记录状态变化、回顾和关键决策事实';
COMMENT ON COLUMN task_event.id IS '任务事件唯一标识';
COMMENT ON COLUMN task_event.user_id IS '所属用户标识，用于数据隔离和时间线查询';
COMMENT ON COLUMN task_event.task_id IS '关联的任务标识';
COMMENT ON COLUMN task_event.event_type IS '稳定的事件类型代码';
COMMENT ON COLUMN task_event.payload_json IS '事件特有的结构化补充数据';
COMMENT ON COLUMN task_event.occurred_at IS '业务事件实际发生时间';
COMMENT ON COLUMN task_event.recorded_at IS '服务端写入该事件的时间';

COMMENT ON TABLE review_session IS '每日或每周复盘会话，记录复盘周期、状态和完成时间';
COMMENT ON COLUMN review_session.id IS '复盘会话唯一标识';
COMMENT ON COLUMN review_session.user_id IS '所属用户标识，用于数据隔离';
COMMENT ON COLUMN review_session.review_type IS '复盘类型：DAILY 每日复盘、WEEKLY 每周复盘';
COMMENT ON COLUMN review_session.period_start IS '复盘覆盖周期的开始日期';
COMMENT ON COLUMN review_session.period_end IS '复盘覆盖周期的结束日期';
COMMENT ON COLUMN review_session.status IS '会话状态：OPEN 进行中、COMPLETED 已完成';
COMMENT ON COLUMN review_session.started_at IS '复盘开始时间';
COMMENT ON COLUMN review_session.completed_at IS '复盘完成时间；未完成时为空';
COMMENT ON COLUMN review_session.created_at IS '复盘会话记录创建时间';

COMMENT ON TABLE review_item IS '复盘会话中的待判断事项，保存触发原因、用户决定及决定参数';
COMMENT ON COLUMN review_item.id IS '复盘事项唯一标识';
COMMENT ON COLUMN review_item.review_session_id IS '所属复盘会话标识；删除会话时级联删除';
COMMENT ON COLUMN review_item.entity_type IS '被复盘实体类型：TASK 任务、PROJECT 项目';
COMMENT ON COLUMN review_item.entity_id IS '被复盘任务或项目的唯一标识';
COMMENT ON COLUMN review_item.reason IS '进入复盘队列的稳定原因代码';
COMMENT ON COLUMN review_item.decision IS '用户作出的稳定决定代码；未决定时为空';
COMMENT ON COLUMN review_item.decision_payload IS '决定所需的结构化补充参数';
COMMENT ON COLUMN review_item.decided_at IS '作出决定的时间';

COMMENT ON TABLE sync_mutation IS '客户端同步变更的幂等处理台账，防止同一操作重复应用并保留冲突结果';
COMMENT ON COLUMN sync_mutation.user_id IS '所属用户标识，与客户端变更标识共同构成主键';
COMMENT ON COLUMN sync_mutation.client_mutation_id IS '客户端生成的全局唯一变更标识，用于幂等去重';
COMMENT ON COLUMN sync_mutation.device_id IS '发起变更的客户端设备标识';
COMMENT ON COLUMN sync_mutation.entity_type IS '变更实体类型，例如 TASK、PROJECT 或 DAILY_PLAN';
COMMENT ON COLUMN sync_mutation.entity_id IS '变更实体唯一标识';
COMMENT ON COLUMN sync_mutation.operation IS '同步操作：UPSERT 新增或更新、DELETE 删除';
COMMENT ON COLUMN sync_mutation.base_revision IS '客户端执行变更时已知的服务端版本号；新实体通常为 0';
COMMENT ON COLUMN sync_mutation.payload_json IS '客户端提交的实体数据或变更数据';
COMMENT ON COLUMN sync_mutation.occurred_at IS '变更在客户端实际发生的时间';
COMMENT ON COLUMN sync_mutation.received_at IS '服务端收到并登记变更的时间';
COMMENT ON COLUMN sync_mutation.result_status IS '处理结果：APPLIED 已应用、ALREADY_APPLIED 已处理、REJECTED 已拒绝、CONFLICT 冲突';
COMMENT ON COLUMN sync_mutation.result_revision IS '变更处理完成后的实体服务端版本号';
COMMENT ON COLUMN sync_mutation.server_sequence IS '成功变更对应的服务端增量序列号';
COMMENT ON COLUMN sync_mutation.error_code IS '拒绝或冲突时返回的稳定错误代码';
COMMENT ON COLUMN sync_mutation.result_payload IS '处理结果、合并结果或冲突详情的结构化数据';

COMMENT ON TABLE change_log IS '服务端增量变更日志，客户端按序列号拉取以恢复多设备一致状态';
COMMENT ON COLUMN change_log.server_sequence IS '服务端单调递增序列号，也是增量同步游标';
COMMENT ON COLUMN change_log.user_id IS '所属用户标识，用于隔离各用户的变更流';
COMMENT ON COLUMN change_log.entity_type IS '发生变化的实体类型';
COMMENT ON COLUMN change_log.entity_id IS '发生变化的实体唯一标识';
COMMENT ON COLUMN change_log.operation IS '变更操作：UPSERT 新增或更新、DELETE 删除';
COMMENT ON COLUMN change_log.revision IS '变更完成后的实体服务端版本号';
COMMENT ON COLUMN change_log.payload_json IS '供客户端应用的实体快照或删除信息';
COMMENT ON COLUMN change_log.created_at IS '服务端生成该增量日志的时间';

COMMENT ON TABLE account_deletion_request IS '账户删除申请表，仅记录最终确认前的限时申请，不直接执行账户删除';
COMMENT ON COLUMN account_deletion_request.id IS '账户删除申请唯一标识';
COMMENT ON COLUMN account_deletion_request.user_id IS '提出删除申请的用户标识';
COMMENT ON COLUMN account_deletion_request.status IS '申请状态：AWAITING_FINAL_CONFIRMATION 等待最终确认、CANCELED 已取消、EXPIRED 已过期';
COMMENT ON COLUMN account_deletion_request.created_at IS '删除申请创建时间';
COMMENT ON COLUMN account_deletion_request.expires_at IS '删除申请失效时间';
