import { zhCN } from "@nextone/i18n";

export const copy = {
  appName: zhCN.app.name,
  today: zhCN.nav.today,
  inbox: zhCN.nav.inbox,
  settings: zhCN.nav.settings,
  capture: zhCN.shell.quickCapture,
  todayTitle: zhCN.today.title,
  todayDescription: zhCN.today.description,
  focus: zhCN.today.focus,
  doing: zhCN.today.doing,
  later: zhCN.today.later,
  emptyFocus: zhCN.today.emptyFocus,
  emptyDoing: zhCN.today.emptyDoing,
  emptyLater: zhCN.today.emptyLater,
  inboxTitle: zhCN.inbox.title,
  inboxDescription: zhCN.inbox.description,
  inboxEmpty: zhCN.inbox.emptyTitle,
  capturePlaceholder: zhCN.capture.placeholder,
  captureNote: zhCN.capture.note,
  captureNotePlaceholder: zhCN.capture.notePlaceholder,
  captureSubmit: zhCN.capture.submit,
  cancel: zhCN.common.cancel,
  save: zhCN.common.save,
  saving: zhCN.common.saving,
  addToday: zhCN.task.addToday,
  status: zhCN.status,
  action: zhCN.action,
} as const;
